# Generated by Django 5.1 on 2024-09-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='client',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='project_details',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='project_id',
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('Clarification', 'Clarification')], default='pending', max_length=20),
        ),
    ]
