# Generated by Django 5.1 on 2024-09-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_clientprofile_alter_businessdetails_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='client',
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('Clarification', 'Clarification')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
