# Generated by Django 5.1 on 2024-09-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_businessdetails_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='myapp.client'),
        ),
    ]
