# Generated by Django 5.1 on 2024-09-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_businessdetails_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='sl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
