# Generated by Django 5.1 on 2024-09-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_state_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='sl',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
