# Generated by Django 5.1 on 2024-09-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_businessdetails_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('clarification', 'Clarification')], default='pending', max_length=20),
        ),
    ]
