# Generated by Django 5.1 on 2024-09-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_businessdetails_loan_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='sl',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
