# Generated by Django 5.1 on 2024-09-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_businessdetails_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='sl',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
