# Generated by Django 5.1 on 2024-09-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_businessdetails_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='company name', max_length=255),
            preserve_default=False,
        ),
    ]
